/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AuthenticatedPostsNewRouteImport } from './routes/_authenticated/posts/new'
import { Route as AuthenticatedPostsPostIdRouteImport } from './routes/_authenticated/posts/$postId'
import { Route as AuthenticatedAccountAccountViewRouteImport } from './routes/_authenticated/account/$accountView'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostsNewRoute = AuthenticatedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostsPostIdRoute =
  AuthenticatedPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountAccountViewRoute =
  AuthenticatedAccountAccountViewRouteImport.update({
    id: '/account/$accountView',
    path: '/account/$accountView',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/$authView': typeof AuthAuthViewRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
}
export interface FileRoutesByTo {
  '/auth/$authView': typeof AuthAuthViewRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth/$authView': typeof AuthAuthViewRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/_authenticated/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/_authenticated/posts/new': typeof AuthenticatedPostsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/$authView'
    | '/'
    | '/account/$accountView'
    | '/posts/$postId'
    | '/posts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/$authView'
    | '/'
    | '/account/$accountView'
    | '/posts/$postId'
    | '/posts/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth/$authView'
    | '/_authenticated/'
    | '/_authenticated/account/$accountView'
    | '/_authenticated/posts/$postId'
    | '/_authenticated/posts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthAuthViewRoute: typeof AuthAuthViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/posts/new': {
      id: '/_authenticated/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthenticatedPostsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/$postId': {
      id: '/_authenticated/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthenticatedPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/$accountView': {
      id: '/_authenticated/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AuthenticatedAccountAccountViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountAccountViewRoute: typeof AuthenticatedAccountAccountViewRoute
  AuthenticatedPostsPostIdRoute: typeof AuthenticatedPostsPostIdRoute
  AuthenticatedPostsNewRoute: typeof AuthenticatedPostsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountAccountViewRoute: AuthenticatedAccountAccountViewRoute,
  AuthenticatedPostsPostIdRoute: AuthenticatedPostsPostIdRoute,
  AuthenticatedPostsNewRoute: AuthenticatedPostsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthAuthViewRoute: AuthAuthViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
